FROM quay.io/fedora/fedora:rawhide AS builder

ARG LLAMA_PR
ARG LLAMA_MERGE
ARG LLAMA_REF
ARG LLAMA_STRATEGY
ENV LLAMA_PR=${LLAMA_PR}
ENV LLAMA_MERGE=${LLAMA_MERGE}
ENV LLAMA_REF=${LLAMA_REF}
ENV LLAMA_STRATEGY=${LLAMA_STRATEGY}

COPY scripts/build_llama.sh scripts/lib.sh src/chat_template.jinja /src/
WORKDIR /src/
RUN ./build_llama.sh mesa

FROM quay.io/fedora/fedora:rawhide

COPY src/chat_template.jinja /src/

RUN --mount=type=bind,from=builder,source=/tmp/install,target=/tmp/install,relabel=private \
    --mount=type=bind,from=builder,source=/tmp/llama-templates,target=/tmp/llama-templates,relabel=private \
    cp -a /tmp/install/bin/ /usr/ && \
    cp -a /tmp/install/lib64/*.so* /usr/lib64/ && \
    mkdir -p /usr/share/llama.cpp/templates && \
    cp -a /tmp/llama-templates/* /usr/share/llama.cpp/templates/ && \
    mkdir -p /custom && \
    cp /src/chat_template.jinja /custom/chat_template.jinja



RUN --mount=type=bind,target=/src,relabel=private \
    /src/scripts/build_llama.sh mesa runtime

WORKDIR /
